### PR TITLE
Tell Rails 4 to automatically precompile images

### PR DESCRIPTION
**Pull request by andycox**
As of Rails 4, image assets in `vendor/assets` are no longer automatically precompiled, including those from gems (see rails/rails#7968). This means that `tipsy.gif` is excluded by default when deploying to production. 

Rather than forcing users to muck around with `environments/production.rb` to include images, it makes sense to change the default to include the relevant images. It appears that the preferred way to do this is to add `tipsy.gif` to `config.assets.precompile` in the Rails engine, as in twbs/bootstrap-sass#391.

If you prefer, an alternative is to rename `vendor/assets` to `app/assets` as images in a gem's `app/assets` are precompiled by default. (I tried that first before discovering the preferred technique.) This approach is similar to how other similar gems are dealing with this (e.g., https://github.com/joliss/jquery-ui-rails/pull/39).

### CODE REVIEW

**Comment by nragaz** [comment]
Thanks! I haven't been able to update to Rails 4 yet so I don't run into these things.

**Comment by andycox** [comment]
Sorry, I probably should've bumped the version so you can push a new gem. Do you want me to do that and submit a new PR?

**Comment by nragaz** [comment]
NP, I'll do it.

**Comment by andycox** [comment]
Thanks!

**Pull request merged**
